# Generated by Django 2.2.3 on 2020-03-23 19:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cookhub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creationDate',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 3, 23, 19, 26, 27, 675293, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='creationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 23, 19, 26, 27, 673303, tzinfo=utc)),
        ),
    ]
