# Generated by Django 2.2.3 on 2020-03-26 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookhub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='saved_recipes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cookhub.Recipe'),
        ),
    ]
