# Generated by Django 2.2.3 on 2020-03-11 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookhub', '0002_auto_20200310_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='profile_picture',
            new_name='picture',
        ),
    ]
