# Generated by Django 2.2.3 on 2020-03-23 19:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cookhub', '0002_auto_20200323_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creationDate',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 3, 23, 19, 28, 9, 568392, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='creationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 23, 19, 28, 9, 566394, tzinfo=utc)),
        ),
    ]
