# Generated by Django 2.2.3 on 2020-03-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookhub', '0002_usermodel_saved_recipes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='saved_recipes',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='saved_recipes',
            field=models.ManyToManyField(blank=True, to='cookhub.Recipe'),
        ),
    ]
