# Generated by Django 2.2.3 on 2020-03-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookhub', '0005_category_comment_ingredient_rating_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.IntegerField(default=1),
        ),
    ]
