# Generated by Django 2.2.3 on 2020-03-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookhub', '0006_auto_20200316_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='recipe_images'),
        ),
    ]
