# Generated by Django 2.2.3 on 2020-03-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookhub', '0014_auto_20200316_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='recipe_images/'),
        ),
    ]
