# Generated by Django 2.2.3 on 2020-03-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookhub', '0015_auto_20200316_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientArray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
