# Generated by Django 2.2.3 on 2020-03-18 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookhub', '0016_ingredientarray'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
    ]
