# Generated by Django 2.2.3 on 2020-03-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookhub', '0021_auto_20200318_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creationDate',
            field=models.DateField(blank=True),
        ),
    ]
