# Generated by Django 2.2.3 on 2020-03-19 16:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cookhub', '0023_auto_20200319_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creationDate',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 3, 19, 16, 32, 8, 821440, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='averageRating',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='creationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 19, 16, 32, 8, 821440, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='views',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
