# Generated by Django 2.2.3 on 2020-03-19 16:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cookhub', '0024_auto_20200319_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creationDate',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 3, 19, 16, 39, 22, 418071, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='categories',
            field=models.ManyToManyField(blank=True, default=None, to='cookhub.Category'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='creationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 19, 16, 39, 22, 402446, tzinfo=utc)),
        ),
    ]
