# Generated by Django 2.2.3 on 2020-03-23 15:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cookhub', '0026_auto_20200320_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creationDate',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 3, 23, 15, 22, 5, 343878, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='creationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 23, 15, 22, 5, 343878, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
